services:
  db-mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ounass_source
      MYSQL_USER: user
      MYSQL_PASSWORD: db123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/mysql_source/initdb:/docker-entrypoint-initdb.d
    networks:
      - etl_network

  db-postgres:
    image: postgres:13
    container_name: postgres_dw
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg123
      POSTGRES_DB: data_warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/postgres_data_warehouse/initdb:/docker-entrypoint-initdb.d
    networks:
      - etl_network

  airflow-init:
      image: apache/airflow:2.9.1
      depends_on:
        - db-postgres
      environment:
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:pg123@db-postgres:5432/data_warehouse
      volumes:
        - ./dags:/opt/airflow/dags
        - ./sql:/opt/airflow/sql
        - ./logs:/opt/airflow/logs
        - ./plugins:/opt/airflow/plugins
        - ./variables.json:/opt/airflow/variables.json
      entrypoint: >
        bash -c "
          airflow db init || airflow db migrate &&
          airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
          airflow pools set db_pool 4 'Limit DB-intensive tasks' || true &&
          airflow pools set db_pool_max 16 'Max Limit DB-intensive tasks' || true &&
          airflow connections delete 'mysql_default' || true &&
          airflow connections add 'mysql_default' \
            --conn-type 'mysql' \
            --conn-login 'user' \
            --conn-password 'db123' \
            --conn-host 'db-mysql' \
            --conn-port '3306' \
            --conn-schema 'ounass_source' \
            --conn-extra '{"charset": "utf8mb4"}' || true && 
          airflow connections delete 'postgres_default' || true &&
          airflow connections add 'postgres_default' \
            --conn-type 'postgres' \
            --conn-login 'postgres' \
            --conn-password 'pg123' \
            --conn-host 'db-postgres' \
            --conn-port '5432' \
            --conn-schema 'data_warehouse' || true &&
          airflow variables import /opt/airflow/variables.json || true
        "

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow-webserver
    depends_on:
      - airflow-init
      - db-mysql
      - db-postgres
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__PARALLELISM: 16              # Max concurrent task instances overall
      AIRFLOW__CORE__DAG_CONCURRENCY: 16          # Max tasks per DAG
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 4  # Max DAG runs at once      
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:pg123@db-postgres:5432/data_warehouse
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.session"
      AIRFLOW__WEBSERVER__RBAC: "True"
      AIRFLOW__CORE__TEST_CONNECTION: "Enabled"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - etl_network
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
      - db-mysql
      - db-postgres
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__PARALLELISM: 16              # Max concurrent task instances overall
      AIRFLOW__CORE__DAG_CONCURRENCY: 16          # Max tasks per DAG
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 4  # Max DAG runs at once      
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:pg123@db-postgres:5432/data_warehouse
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - etl_network
    command: scheduler

volumes:
  mysql_data:
  postgres_data:

networks:
  etl_network:
    driver: bridge
